# Generated by Django 2.0.1 on 2018-01-09 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='score',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
