# Generated by Django 2.0.1 on 2018-01-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20180109_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'Text question'), ('option', 'One of provided options'), ('score', '1-5 Score range')], default='score', max_length=50),
        ),
        migrations.RunSQL("UPDATE poll_question SET type = 'option' WHERE type = 'options';")
    ]
