version: '2'
services:
  database:
    image: postgres

  backend:
    build: src/backend
    volumes:
      - ./src/backend:/srv
    ports:
      - 8000:8000
    command: wait-for-it.sh -t 10 database:5432 -- python -u manage.py runserver 0.0.0.0:8000