#!/usr/bin/env bash

# go back to root dir
cd "${0%/*}/.."


echo "Creating migrations..."
docker-compose run --rm backend python manage.py makemigrations $@
docker-compose run --rm backend chown -R $UID .
